disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - explicit_init
  # TODO: Consider adding custom rule to enforce nonisolated keyword consistency
  # for actor methods that don't need isolation (synchronous, pure functions)

included:
  - VideoHelper

excluded:
  - Pods
  - build
  - .build
  - VideoHelperTests
  - VideoHelperUITests

line_length:
  warning: 120
  error: 200

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 60
