disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - explicit_init

included:
  - VideoHelper

excluded:
  - Pods
  - build
  - .build
  - VideoHelperTests
  - VideoHelperUITests

line_length:
  warning: 120
  error: 200

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 60
